[package]
name = "realworld-tide"
version = "0.1.0"
authors = ["colinbankier <colinbankier@gmail.com>"]
edition = "2018"

[dependencies]
tide = { git = "https://github.com/rust-net-web/tide.git" }
diesel = { version = "1.3.3", features = ["postgres", "extras"] }
r2d2 = "0.8.3"
serde = "1.0"
serde_derive = "1.0"
dotenv = "0.9.0"
chrono = { version = "0.4.6", features = ["serde"] }
http = "0.1"
futures = "0.1"
tokio = { version = "0.1.13", features = ["async-await-preview"] }
tokio-threadpool = "0.1.9"
log = "0.4.0"
env_logger = "0.6.0"
jsonwebtoken = "5.0.1"
tokio-async-await-test = "0.1"

[dependencies.futures-preview]
features = ["compat", "tokio-compat"]
version = "0.3.0-alpha.12"
